library(readxl)
energyconsumtion <- read_excel("C:/Users/jortega/Downloads/energyconsumtion.xlsx")
View(energyconsumtion)
png(filename = "Plot1.png")
hist(energyconsumtion$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()